<#
.SYNOPSIS
    ServerPinger installer for Windows.

.DESCRIPTION
    Creates a virtualenv, installs pinned requirements, initialises the database
    and registers ServerPinger to start automatically.

    Registration methods:
      Nssm          - NSSM service wrapper (best option; needs nssm.exe on PATH)
      Sc            - sc.exe service against a .cmd wrapper (see the README caveat)
      ScheduledTask - Task Scheduler "at startup, whether logged on or not"
                      (the fallback when you cannot install a service)
      Auto          - Nssm if nssm.exe is present, otherwise ScheduledTask
      None          - install only, register nothing

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\deploy\install.ps1

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\deploy\install.ps1 -Port 9000 -Method ScheduledTask
#>
[CmdletBinding()]
param(
    [int]$Port = 8282,
    [string]$BindAddress = "0.0.0.0",
    [string]$DataDir = "",
    [ValidateSet("Auto", "Nssm", "Sc", "ScheduledTask", "None")]
    [string]$Method = "Auto",
    [string]$Python = "python",
    [switch]$OpenFirewall
)

$ErrorActionPreference = "Stop"

$AppDir = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$Venv = Join-Path $AppDir ".venv"
$VenvPython = Join-Path $Venv "Scripts\python.exe"
$VenvPythonW = Join-Path $Venv "Scripts\pythonw.exe"
$ServiceName = "ServerPinger"

if ([string]::IsNullOrWhiteSpace($DataDir)) {
    if ($env:SERVERPINGER_DATA) {
        $DataDir = $env:SERVERPINGER_DATA
    } else {
        $DataDir = Join-Path $env:PROGRAMDATA "ServerPinger"
    }
}

function Test-Admin {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

Write-Output "==> App directory:  $AppDir"
Write-Output "==> Data directory: $DataDir"

# --- python + venv ---------------------------------------------------------
$pythonCmd = Get-Command $Python -ErrorAction SilentlyContinue
if ($null -eq $pythonCmd) {
    throw "Python not found on PATH. Install Python 3.9 or newer, or pass -Python <path>."
}
Write-Output "==> Using $($pythonCmd.Source)"

Write-Output "==> Creating virtualenv"
& $pythonCmd.Source -m venv $Venv
if ($LASTEXITCODE -ne 0) { throw "Failed to create the virtualenv." }

Write-Output "==> Installing requirements"
& $VenvPython -m pip install --upgrade pip | Out-Null
& $VenvPython -m pip install -r (Join-Path $AppDir "requirements.txt")
if ($LASTEXITCODE -ne 0) { throw "pip install failed." }

# --- database --------------------------------------------------------------
Write-Output "==> Initialising database"
if (-not (Test-Path $DataDir)) { New-Item -ItemType Directory -Path $DataDir -Force | Out-Null }
$env:SERVERPINGER_DATA = $DataDir
& $VenvPython (Join-Path $AppDir "run.py") --init-db
if ($LASTEXITCODE -ne 0) { throw "Database initialisation failed." }

# --- a wrapper the service / task can launch -------------------------------
$wrapper = Join-Path $AppDir "deploy\serverpinger-service.cmd"
$wrapperBody = @"
@echo off
REM Generated by deploy\install.ps1 - launches ServerPinger with its environment.
set SERVERPINGER_DATA=$DataDir
set SERVERPINGER_HOST=$BindAddress
set SERVERPINGER_PORT=$Port
set PYTHONUNBUFFERED=1
cd /d "$AppDir"
"$VenvPython" "$AppDir\run.py"
"@
Set-Content -Path $wrapper -Value $wrapperBody -Encoding ASCII
Write-Output "==> Wrote launcher $wrapper"

# --- registration ----------------------------------------------------------
$nssm = Get-Command nssm.exe -ErrorAction SilentlyContinue
$chosen = $Method
if ($chosen -eq "Auto") {
    if ($null -ne $nssm) { $chosen = "Nssm" } else { $chosen = "ScheduledTask" }
}

if ($chosen -ne "None" -and -not (Test-Admin)) {
    Write-Warning "Not running as Administrator - skipping service registration."
    Write-Warning "Re-run this script from an elevated PowerShell, or start it by hand:"
    Write-Warning "  $wrapper"
    $chosen = "None"
}

switch ($chosen) {
    "Nssm" {
        if ($null -eq $nssm) { throw "nssm.exe is not on PATH. Use -Method ScheduledTask instead." }
        Write-Output "==> Registering the $ServiceName service with NSSM"
        & $nssm.Source stop $ServiceName 2>$null | Out-Null
        & $nssm.Source remove $ServiceName confirm 2>$null | Out-Null
        & $nssm.Source install $ServiceName $VenvPython (Join-Path $AppDir "run.py")
        & $nssm.Source set $ServiceName AppDirectory $AppDir
        & $nssm.Source set $ServiceName AppEnvironmentExtra "SERVERPINGER_DATA=$DataDir" "SERVERPINGER_HOST=$BindAddress" "SERVERPINGER_PORT=$Port" "PYTHONUNBUFFERED=1"
        & $nssm.Source set $ServiceName Start SERVICE_AUTO_START
        & $nssm.Source set $ServiceName AppExit Default Restart
        & $nssm.Source set $ServiceName AppRestartDelay 5000
        & $nssm.Source start $ServiceName
        Write-Output "==> Service installed. Manage it with: nssm restart $ServiceName"
    }
    "Sc" {
        Write-Output "==> Registering the $ServiceName service with sc.exe"
        Write-Warning "sc.exe expects a real service binary. A .cmd wrapper usually reports"
        Write-Warning "error 1053 on start. Prefer -Method Nssm or -Method ScheduledTask."
        & sc.exe stop $ServiceName | Out-Null
        & sc.exe delete $ServiceName | Out-Null
        & sc.exe create $ServiceName binPath= "cmd.exe /c `"$wrapper`"" start= auto DisplayName= "ServerPinger"
        & sc.exe description $ServiceName "ServerPinger reachability monitor"
        & sc.exe failure $ServiceName reset= 60 actions= restart/5000/restart/5000/restart/5000
        & sc.exe start $ServiceName
    }
    "ScheduledTask" {
        Write-Output "==> Registering the $ServiceName scheduled task (at startup)"
        $action = New-ScheduledTaskAction -Execute "cmd.exe" -Argument "/c `"$wrapper`"" -WorkingDirectory $AppDir
        $trigger = New-ScheduledTaskTrigger -AtStartup
        $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
        $taskSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries `
            -DontStopIfGoingOnBatteries -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
            -ExecutionTimeLimit ([TimeSpan]::Zero) -StartWhenAvailable
        Unregister-ScheduledTask -TaskName $ServiceName -Confirm:$false -ErrorAction SilentlyContinue
        Register-ScheduledTask -TaskName $ServiceName -Action $action -Trigger $trigger `
            -Principal $principal -Settings $taskSettings -Description "ServerPinger reachability monitor" | Out-Null
        Start-ScheduledTask -TaskName $ServiceName
        Write-Output "==> Task registered. Manage it with: schtasks /query /tn $ServiceName"
    }
    "None" {
        Write-Output "==> Nothing registered. Start ServerPinger manually with:"
        Write-Output "    $wrapper"
    }
}

# --- firewall --------------------------------------------------------------
if ($OpenFirewall) {
    if (Test-Admin) {
        Write-Output "==> Opening TCP $Port in Windows Firewall"
        New-NetFirewallRule -DisplayName "ServerPinger $Port" -Direction Inbound `
            -Action Allow -Protocol TCP -LocalPort $Port -ErrorAction SilentlyContinue | Out-Null
    } else {
        Write-Warning "Not elevated - skipping the firewall rule."
    }
}

$ip = (Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
       Where-Object { $_.IPAddress -ne "127.0.0.1" -and $_.PrefixOrigin -ne "WellKnown" } |
       Select-Object -First 1).IPAddress
if ([string]::IsNullOrWhiteSpace($ip)) { $ip = $env:COMPUTERNAME }

Write-Output ""
Write-Output "ServerPinger is available at:"
Write-Output "  http://localhost:$Port/"
Write-Output "  http://${ip}:$Port/"
Write-Output ""
Write-Output "If another machine cannot reach it, allow the port:"
Write-Output "  New-NetFirewallRule -DisplayName 'ServerPinger $Port' -Direction Inbound -Action Allow -Protocol TCP -LocalPort $Port"
Write-Output "Logs: $DataDir\serverpinger.log"
